security:
    providers:
        token_provider:
            entity:
                class: App\Entity\Token
                property: id
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            logout: ~
            provider: token_provider
            guard:
                authenticators:
                    - App\Security\TokenAuthenticator
            access_denied_handler: App\Security\AccessDeniedHandler

    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
